# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

user = User.create!(name: "Patches", email: "patches@test.com", bio: "meow meow pow pow", password: "password", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvgTg3i3FXRim1-EbDC4Y1_HzJRKC14fphTQ&usqp=CAU")

broadsword = Weapon.create!(name: "Broadsword", description: "a sword with a wide blade, used primarily for cutting rather than thrusting.", image_url: "https://pics.knifecenter.com/knifecenter/united/images/UC3265_1.jpg")
knife = Weapon.create(name: "Knife", description: "an instrument composed of a blade fixed into a handle, used for cutting or as a weapon.", image_url: "https://www.ikea.com/us/en/images/products/vardagen-chefs-knife-dark-gray__0710384_pe727512_s5.jpg?f=s")
quarterstaff = Weapon.create!(name: "Quarterstaff", description: "a long stout staff formerly used as a weapon and wielded with one hand in the middle and the other between the middle and the end.", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWi4PXBEaZfXrYkC3BN7HcSeKrMNH5LeBKRg&usqp=CAU")
rapieranddager = Weapon.create!(name: "Rapier and Dagger", description: "a thin, light sharp-pointed sword used for thrusting and a short knife with a pointed and edged blade", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-njmLMnS_SBNLLR7RXMKdAGaLBkhllnV17w&usqp=CAU")
singlesword = Weapon.create!(name: "Single Sword", description: "a sword with a hilt that is held in one hand, sometimes having only one true edge. ", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDwu1_9d0xVQTw0dpHpGPev9zZcWO7SFCtjbcMzrUn4BO37FpS88JCW6jrfbyXj-Vs2E4&usqp=CAU")
smallsword = Weapon.create(name: "Small Sword", description: "a light, tapering thrusting sword.", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcmBqCjqdxc6qtMB_iweCfGtRDZJ7g4zcxHw&usqp=CAU")
swordandshield = Weapon.create(name: "Sword and Shield ", description: "a bladed weapon held in one hand and a piece of personal armour held in the other.", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhUbZ85JlUaol-eyf0Y_arEsVouvSbxu8chQ&usqp=CAU")
unarmed = Weapon.create!(name: "Unarmed", description: "the action of fighting without weapons.", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgUt4JTwfP3e_wUVYPcDN44IOAYM5xl0Euow&usqp=CAU")

broadsword_move1 = Move.create!(name: "Attack: High Inside", fighter_or_fight: "Fighter", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE ", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move2 = Move.create!(name: "Attack: Low Inside", fighter_or_fight: "Fighter", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move3 = Move.create!(name: "Attack: High Outside", fighter_or_fight: "Fighter", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move4 = Move.create!(name: "Attack: Low Outside", fighter_or_fight: "Fighter", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move5 = Move.create!(name: "Attack: (2 Cuts, 2 Thrust)", fighter_or_fight: "Fight", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move6 = Move.create!(name: "Attack: Bind", fighter_or_fight: "Fight", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move7 = Move.create!(name: "Attack: Slashing Attacks", fighter_or_fight: "Fight", quantity: "2", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move8 = Move.create!(name: "Attack: Corps‐a‐Corps", fighter_or_fight: "Fight", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move9 = Move.create!(name: "Attack: Kill or Non‐debilitating Wound", fighter_or_fight: "Fight", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move10 = Move.create!(name: "Attack: Moulinet", fighter_or_fight: "Fighter", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move11 = Move.create!(name: "Defense: Parry High Inside", fighter_or_fight: "Fighter", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move12 = Move.create!(name: "Defense: Parry Low Inside", fighter_or_fight: "Fighter", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move13 = Move.create!(name: "Defense: Parry High Outside", fighter_or_fight: "Fighter", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move14 = Move.create!(name: "Defense: Parry Low Outside", fighter_or_fight: "Fighter", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move15 = Move.create!(name: "Footwork: Pass Forward", fighter_or_fight: "Fight", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move16 = Move.create!(name: "Footwork: Pass Back", fighter_or_fight: "Fight", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move17 = Move.create!(name: "Footwork: Circular Sequence", fighter_or_fight: "Fight", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move18 = Move.create!(name: "Footwork: Off Line Sequence", fighter_or_fight: "Fight", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")
broadsword_move19 = Move.create!(name: "Footwork: Running Attack", fighter_or_fight: "Fight", quantity: "1", description: "REPLACE: DESCRIPTION OF MOVE HERE", weapon: broadsword, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHaB9Ig_aSUS05M48ohGmGpzSBZWRO1kZ0IA&usqp=CAU", video_url: "https://youtu.be/vJGvSbHmeco?si=fIzJ9GRfyWptw3I8")

SelectedMove.create!(user: user, move: broadsword_move8)
SelectedMove.create!(user: user, move: broadsword_move6)
SelectedMove.create!(user: user, move: broadsword_move17)